"""Iniciar

Revision ID: 8378893754b9
Revises: 
Create Date: 2024-03-12 15:13:03.473834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8378893754b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('activityDescription', sa.Text(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('asset_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assetId', sa.Integer(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('closingPrice', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('openingPrice', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_price_history_dateTime'), 'asset_price_history', ['dateTime'], unique=False)
    op.create_index(op.f('ix_asset_price_history_id'), 'asset_price_history', ['id'], unique=False)
    op.create_table('asset_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assetId', sa.Integer(), nullable=False),
    sa.Column('projectionDate', sa.DateTime(), nullable=False),
    sa.Column('projectedPrice', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('projectionMethod', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_projections_id'), 'asset_projections', ['id'], unique=False)
    op.create_index(op.f('ix_asset_projections_projectionDate'), 'asset_projections', ['projectionDate'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('assetId', sa.Integer(), nullable=False),
    sa.Column('triggerPrice', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('alertType', sa.Enum('above', 'below'), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_id'), 'price_alerts', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('visualizationSettings', sa.Text(), nullable=True),
    sa.Column('notificationSettings', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('portfolio_asset_details',
    sa.Column('portfolioId', sa.Integer(), nullable=False),
    sa.Column('assetId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('averageAcquisitionValue', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('currentValue', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('profitability', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolioId'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('portfolioId', 'assetId')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolioId', sa.Integer(), nullable=False),
    sa.Column('assetId', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('buy', 'sell'), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('transactionDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolioId'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('portfolio_asset_details')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_price_alerts_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_asset_projections_projectionDate'), table_name='asset_projections')
    op.drop_index(op.f('ix_asset_projections_id'), table_name='asset_projections')
    op.drop_table('asset_projections')
    op.drop_index(op.f('ix_asset_price_history_id'), table_name='asset_price_history')
    op.drop_index(op.f('ix_asset_price_history_dateTime'), table_name='asset_price_history')
    op.drop_table('asset_price_history')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
